services:
  postgres:
    image: postgres:16-alpine
    container_name: security-tool-db
    environment:
      POSTGRES_USER: brand
      POSTGRES_PASSWORD: 98741
      POSTGRES_DB: security_tool_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
